### ISSUE TITLE
Remove transliterate module

### ISSUE THREAD

**Issue by vvasuki** [sanskrit/sanskrit#6]
I'd updated in https://github.com/sanskrit/sanskrit/issues/2 : " Packaged the transliteration part ( https://pypi.python.org/pypi/indic-transliteration ) - possibly good idea to update readme to redirect there."

All useful code from the transliterate module should be moved to and maintained at  https://pypi.python.org/pypi/indic-transliteration  - that way we can deduplicate and maintain the code at a single place.

**Comment by vvasuki** [comment]
I could help with this if @avinashvarna or @akprasad add me

**Comment by avinashvarna** [comment]
I agree that this is a good idea. I have been leery of making invasive changes, since I was not the original developer of the code and don't understand all the details. If you are also willing to help out and review the changes, it gives me greater confidence to make changes.

I only have write permissions to this repo, so I can add you to the fork I am maintaining for now. @akprasad will have to add you to the main repo.

**Comment by vvasuki** [comment]
The module wasnt being used anywhere. Removed it from your repo. Closing this bug.
